services:
  _defaults:
    autowire: true
    autoconfigure: true

  # PDO Session Handler — DATABASE_URL-аа ашиглана
  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
    arguments:
      - '%env(resolve:DATABASE_URL)%'
