# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'

  # CSRF хамгаалалт (form_login, бүртгэлд)
  csrf_protection: true

  # Session (CSRF/Form/Login-д хэрэгтэй) — тогтмол save_path заая
  session:
    handler_id: null
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    name: MICROFINSESSID
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true

  # Form component
  form: true

  # Router
  router:
    utf8: true

  http_method_override: false

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
