# config/packages/framework.yaml
framework:
  secret: '%env(APP_SECRET)%'
  handle_all_throwables: true

  csrf_protection: true
  form: true
  http_method_override: false

  # ✅ Proxy / Host тохиргоо (Render/Cloudflare)
  trusted_proxies: ['127.0.0.1', 'REMOTE_ADDR']
  trusted_headers: ['x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-host']
  trusted_hosts:
    - '^microfin-ui52\.onrender\.com$'
    - '^localhost$'
    - '^127\.0\.0\.1$'

  # ✅ Session — ЗӨВХӨН нэг блок (DB handler ашиглана)
  session:
    enabled: true
    handler_id: 'session.handler.pdo'        # services.yaml дээрээ session.handler.pdo заасан байх ёстой
    storage_factory_id: session.storage.factory.native
    name: SFSESSID
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true
    cookie_lifetime: 0
    gc_maxlifetime: 14400

  router:
    utf8: true

  php_errors:
    log: true

  # ✅ Login throttle (rate limiter)
  rate_limiter:
    login:
      policy: fixed_window
      limit: 5
      interval: '1 minute'

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
