# config/packages/framework.yaml
framework:
  secret: '%env(APP_SECRET)%'

  # ✅ CSRF хамгаалалт
  csrf_protection: true

  # ✅ Reverse proxy/host итгэлцэл (Render зэрэг орчинд заавал)
  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_hosts: '%env(regex:TRUSTED_HOSTS)%'
  trusted_headers:
    - x-forwarded-for
    - x-forwarded-proto
    - x-forwarded-port
    - x-forwarded-host

  # ✅ Session тохиргоо (cookie + хугацаа)
  session:
    handler_id: null
    name: SFSESSID            # шинэ cookie нэр (хуучин session-уудыг хүчингүй болгоно)
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true
    cookie_lifetime: 0
    gc_maxlifetime: 14400

  # ✅ Форм компонент
  form: true

  # ✅ Роутер
  router:
    utf8: true

  # ✅ HTTP method override хэрэггүй
  http_method_override: false

  # ✅ Нэвтрэлтийн хурд хязгаарлалт
  rate_limiter:
    login:
      policy: fixed_window
      limit: 5
      interval: '1 minute'

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
