# config/packages/framework.yaml
framework:
  secret: '%env(APP_SECRET)%'

  csrf_protection: true

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true

  form: true

  router:
    utf8: true

  http_method_override: false

  # ✅ Login throttling-д ашиглах rate limiter
  rate_limiter:
    login:
      policy: 'fixed_window'
      limit: 5           # 1 минутанд 5 удаа оролдлого
      interval: '1 minute'

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
