# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'

  csrf_protection: true

  # Session: PDO handler -> Postgres руу хадгална
  session:
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true
    name: MICROFINSESSID

  form: true

  router:
    utf8: true

  http_method_override: false

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
