framework:
  secret: '%env(APP_SECRET)%'

  csrf_protection: true

  # Native (file) sessions — PdoSessionHandler БАЙХГҮЙ
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true

  form: true

  router:
    utf8: true

  translator:
    enabled: true
    fallbacks: ['en']

  http_method_override: false

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
