# config/packages/framework.yaml
framework:
  secret: '%env(APP_SECRET)%'

  csrf_protection: true

  # ✅ Proxy/Host тохиргоо (env шаардахгүй, Render-д шууд OK)
  trusted_proxies: '127.0.0.1,REMOTE_ADDR'
  trusted_hosts:
    - '^microfin-ui52\.onrender\.com$'
    - '^localhost$'
    - '^127\.0\.0\.1$'
  trusted_headers:
    - x-forwarded-for
    - x-forwarded-proto
    - x-forwarded-port
    - x-forwarded-host

  session:
    handler_id: null
    name: SFSESSID
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true
    cookie_lifetime: 0
    gc_maxlifetime: 14400

  form: true

  router:
    utf8: true

  http_method_override: false

  rate_limiter:
    login:
      policy: fixed_window
      limit: 5
      interval: '1 minute'

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
