# config/packages/framework.yaml
framework:
  secret: '%env(APP_SECRET)%'

  csrf_protection: true

  session:
    handler_id: null
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    cookie_secure: auto
    cookie_samesite: lax
    cookie_httponly: true
    cookie_lifetime: 0   # browser session
    gc_probability: 1
    gc_divisor: 100

  form: true
  router:
    utf8: true
  http_method_override: false

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
