databases:
  - name: mini-finance-db
    plan: starter

services:
  - type: web
    name: mini-finance
    env: php
    plan: starter
    region: frankfurt
    autoDeploy: true
    healthCheckPath: /healthz

    buildCommand: |
      composer install --no-dev --optimize-autoloader

    startCommand: php -S 0.0.0.0:$PORT public/index.php

    postdeployCommand: php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: OPENING_BALANCE
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mini-finance-db
      - key: SYMFONY_TRUSTED_PROXIES
        value: "0.0.0.0/0,::/0"
      - key: SYMFONY_TRUSTED_HOSTS
        value: ".onrender.com"
