controllers:
  resource: ../src/Controller/
  type: attribute

public_home:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'public/home.html.twig' }

public_intro:
  path: /intro
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'public/intro.html.twig' }

public_guide:
  path: /guide
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'public/guide.html.twig' }

public_pricing:
  path: /pricing
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'public/pricing.html.twig' }

public_contact:
  path: /contact
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'public/contact.html.twig' }

app_home:
  path: /app
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults: { route: bank_reports_home, permanent: false }

# ⬇️ Дансны хуулгын ROUTE-уудыг жинхэнэ Controller action руу холбоно
bank_reports_home:
  path: /app/reports/bank
  controller: App\Controller\ReportController::summary


bank_reports_import:
  path: /app/reports/bank/import
  controller: App\Controller\ReportController::upload

bank_reports_prepare:
  path: /app/reports/bank/prepare
  controller: App\Controller\ReportController::summary

# ⬇️ Hook to real ProfileController paths
app_profile_home:
  path: /app/profile
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults: { path: /profile, permanent: false }

app_profile_email:
  path: /app/profile/security/email
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults: { path: /profile/change-email, permanent: false }

app_profile_password:
  path: /app/profile/security/password
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults: { path: /profile/change-password, permanent: false }

app_reports_home:
  path: /app/reports
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults: { route: bank_reports_home, permanent: false }

legacy_reports_redirect:
  path: /reports
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults: { route: bank_reports_home, permanent: false }

app_reports_ebarimt_home:
  path: /app/reports/ebarimt
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'reports/ebarimt/index.html.twig' }

app_reports_ebarimt_opening:
  path: /app/reports/ebarimt/opening-balance
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'reports/ebarimt/opening_balance.html.twig' }

app_reports_ebarimt_send:
  path: /app/reports/ebarimt/send
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'reports/ebarimt/send.html.twig' }

app_reports_ebarimt_history:
  path: /app/reports/ebarimt/history
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'reports/ebarimt/history.html.twig' }

bank_reports_statement:
  path: /app/reports/bank/statement
  controller: App\Controller\ReportController::summary