controllers:
public_home:
public_intro:
public_guide:
public_pricing:
public_contact:
app_home:
bank_reports_home:
bank_reports_import:
bank_reports_statement:
  path: /app/reports/bank/statement
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults: { template: 'summary.html.twig' }
